

export const API_ENDPOINT_CONNECTIONS = `/api/connections`;
export const API_ENDPOINT_CONNECTION_SINGLE = `${API_ENDPOINT_CONNECTIONS}/:connectionId`;
export const API_ENDPOINT_CONNECTION_TABLES = `${API_ENDPOINT_CONNECTION_SINGLE}/tables`;