insert into Databases (name, database_type_id, database_name, username, host, password, file) values ('mus etiam vel augue vestibulum rutrum', 1, 'eros viverra', null, '10.184.89.122', 'RWTfATOKSsO', 'DuisMattisEgestas.xls'),
('fermentum justo nec condimentum neque', 1, 'posuere cubilia', null, null, 'I0LjwdLS', 'TortorDuis.xls'),
('ipsum aliquam non mauris morbi non lectus aliquam sit', 2, 'arcu sed augue aliquam', null, '17.25.71.119', 'ARnG7YR', 'ConsequatVariusInteger.mp3'),
('in congue etiam justo etiam pretium', 2, 'turpis sed ante vivamus', 'cridgedell3', null, 'kGUqPM8Ko', null),
('fusce posuere felis', 1, 'scelerisque', 'ggullam4', '253.193.116.25', 'gpow1IoVL3', 'InFaucibusOrci.png'),
('penatibus et magnis dis parturient montes nascetur ridiculus mus', 2, 'curabitur in libero ut massa', 'ebalderstone5', '229.158.63.50', 'XB9aau9k', 'ArcuLibero.xls'),
('cursus urna ut', 1, 'luctus cum', 'mrawcliffe6', '109.209.68.31', 'mTDTHMZ', null),
('nisl duis bibendum felis sed interdum venenatis turpis enim blandit', 1, 'pede morbi porttitor lorem', 'pitzakovitz7', '145.243.203.53', '0UDN6R', null),
('pellentesque volutpat dui maecenas tristique est et tempus semper est', 2, 'quis turpis eget', 'kiveagh8', '182.49.183.48', '7xtVsPZN', 'InterdumEuTincidunt.mp3'),
('vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', 1, 'sapien urna pretium nisl', 'cclipsham9', null, 't8qB4sHXTICq', 'JustoNecCondimentum.ppt'),
('fusce lacus purus aliquet at feugiat non pretium quis lectus', 2, 'montes nascetur', null, '175.255.144.25', 'Xrx2f2shEVX', null),
('est donec odio justo sollicitudin ut', 1, 'et ultrices posuere cubilia curae', 'afaugheyb', '133.193.127.229', 'ESnjMuIkJ3', 'Fusce.avi'),
('consequat varius integer ac', 2, 'enim in', 'hattenbarrowc', '157.230.24.76', 'GqoHDkQKJ', null),
('mattis pulvinar nulla pede', 2, 'varius nulla facilisi', 'amacswayded', '107.242.46.22', 'sNKvzG90fnp', null),
('dolor quis odio consequat varius integer ac', 2, 'nulla eget', 'kbernakiewicze', null, 'jWJk5IoL', null),
('magna bibendum imperdiet nullam orci pede venenatis non', 2, 'lacinia nisi', 'amacsweeneyf', '126.1.170.194', '9AkMX2zq51vQ', null),
('cras in purus eu magna vulputate luctus cum', 2, 'quam fringilla rhoncus mauris enim', 'eangricg', '115.244.16.162', 'eCc4EkBnk', null),
('vitae consectetuer eget rutrum at', 2, 'rhoncus sed vestibulum sit amet', 'wrosencrantzh', null, 'NtDPUjmU', null),
('primis in faucibus', 1, 'donec', null, '109.46.8.33', 'EHnSzKZdUy', null),
('commodo vulputate justo in blandit ultrices', 1, 'rutrum rutrum neque', 'rhartnellj', null, 'XTBlI8', 'Justo.ppt'),
('sit amet justo morbi ut odio cras mi pede malesuada', 1, 'pellentesque quisque', null, '213.25.108.122', '91RwfiV8OR', null),
('lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 2, 'in blandit ultrices', 'lraschl', '111.118.72.121', 'XwjxxSX', 'FermentumDonecUt.xls'),
('potenti cras in purus eu magna vulputate luctus cum', 2, 'odio curabitur convallis duis', 'ewillfordm', '83.6.52.48', '9DOlpa0L', null),
('sodales scelerisque mauris sit amet', 2, 'commodo vulputate justo in blandit', 'bjeenesn', '100.107.174.251', '70aqXq4', null),
('ligula nec sem duis', 2, 'nisi volutpat eleifend', null, '251.109.65.220', 'nRQxIDp', 'AdipiscingLoremVitae.jpeg'),
('odio cras mi pede malesuada in imperdiet et commodo', 2, 'sed magna', 'sabelp', '77.186.158.153', 'POQCuTE2W', 'NatoquePenatibus.doc'),
('aliquet massa id lobortis', 2, 'eget congue', 'kpedroniq', '57.71.180.25', '7AEME3s4', null),
('aliquam quis turpis eget elit sodales scelerisque', 2, 'maecenas rhoncus aliquam lacus', null, '38.27.163.114', 'H9UzDzXW', 'ALibero.tiff'),
('tempus vel pede', 2, 'eros viverra', null, '16.155.101.87', '5mAUvKtsh', null),
('quis justo maecenas', 2, 'massa id lobortis convallis', 'wclowsleyt', '97.114.131.162', 'wIJdoz', 'UltricesPosuere.ppt')